name: todo_list_technical_test
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  file_picker: ^6.1.1
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.9
  formz: ^0.8.0
  freezed_annotation: ^2.4.1
  google_fonts: ^6.2.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  image_picker: ^1.0.7
  json_annotation: ^4.8.1
  just_audio: ^0.9.36
  path: ^1.8.3
  path_provider: ^2.1.2
  photo_view: ^0.14.0
  record: ^5.0.4
  riverpod: ^2.6.1
  riverpod_annotation: ^2.3.3
  speech_to_text: ^7.0.0
  syncfusion_flutter_pdfviewer: ^24.2.9
  uuid: ^4.2.1

dev_dependencies:
  build_runner: ^2.4.7
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.4.6
  hive_generator: ^2.0.1
  json_serializable: ^6.7.1
  riverpod_generator: ^2.3.9

flutter:
  uses-material-design: true
