name: todo_list_technical_test
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  formz: ^0.8.0
  freezed_annotation: ^2.1.0
  google_fonts: ^6.2.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.2
  riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  uuid: ^4.3.3

dev_dependencies:
  build_runner: ^2.4.15
  build_verify: ^3.1.0
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.1.0
  hive_generator: ^2.0.1
  mockito: ^5.4.4
  pubspec_dependency_sorter: ^1.0.5
  riverpod_generator: ^2.3.9
  very_good_analysis: ^8.0.0

flutter:
  uses-material-design: true
